# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzurePowerShell@5
  inputs:
    ScriptType: 'InlineScript'
    Inline: |
      $EmailFrom = "amruta.kulkarni9175@gmail.com”
      
      $EmailTo = “adeshpande@microsoft.com”
      
      $Subject = “The subject of your email”
      
      $Body = “What do you want your email to say”
      
      $SMTPServer = “smtp.gmail.com”
      
      $SMTPClient = New-Object Net.Mail.SmtpClient($SmtpServer, 587)
      
      $SMTPClient.EnableSsl = $true
      
      $SMTPClient.Credentials = New-Object System.Net.NetworkCredential(“usr”, “pass”);
      
      $SMTPClient.Send($EmailFrom, $EmailTo, $Subject, $Body)
    azurePowerShellVersion: 'LatestVersion'